-- Criar tabela de confirmações de presença
create table confirmacoes (
    id bigint generated by default as identity primary key,
    nome text not null,
    telefone text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar tabela de palpites
create table palpites (
    id bigint generated by default as identity primary key,
    peso decimal not null,
    data date not null,
    hora time not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
